# Generated by Django 5.2.4 on 2025-07-26 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Note')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Signalé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='claude_behavioral_patterns',
            field=models.JSONField(blank=True, null=True, verbose_name='Patterns Comportementaux'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='client',
            name='min_transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='client',
            name='night_transactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='weekend_transactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyinsight',
            name='key_patterns',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='claude_risk_factors',
            field=models.JSONField(blank=True, null=True, verbose_name='Facteurs de Risque'),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='ml_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confiance ML'),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='ml_risk_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score de Risque'),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='transaction_day_of_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jour de la semaine'),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='transaction_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='Heure'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['risk_level'], name='fraud_detec_risk_le_02a22a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['fraud_transactions_count'], name='fraud_detec_fraud_t_cd81ff_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['client_i'], name='fraud_detec_client__797b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['client_b'], name='fraud_detec_client__ba0561_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['bank_i'], name='fraud_detec_bank_i_26fad0_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['bank_b'], name='fraud_detec_bank_b_99a2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['transaction_date'], name='fraud_detec_transac_1b0930_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['ml_is_fraud'], name='fraud_detec_ml_is_f_885b7b_idx'),
        ),
        migrations.AddField(
            model_name='transactionnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionnote',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='fraud_detection.rawtransaction'),
        ),
    ]
