# Generated by Django 5.2.4 on 2025-07-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0002_transactionnote_client_claude_behavioral_patterns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_run_analysis',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='can_upload_data',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
