# Generated by Django 5.2.3 on 2025-07-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0003_remove_customuser_can_run_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fraud_rate',
            field=models.FloatField(default=0.0, verbose_name='Taux de Fraude (%)'),
        ),
    ]
